#please note : no '-' is used
kafka:
   appId: kafka-algo-app-1
   bootstrapServers: |
      192.168.56.101:9092
   bootstrapServersTarget: |
      192.168.56.101:9092
   zookeeperHost: 192.168.56.101
   defaultKeySerde: String
   defaultValueSerde: Avro
   appVersion: 46
   appDeltaValue: 100
   appSmallDeltaValue: 1
   appSleepTimeMs: 100
   autoOffsetReset: earliest
   schemaRegistyUrl: http://192.168.56.101:8081/
   topics:
      input-topic-1: input-topic-1
      input-topic-2: input-topic-2
      output-topic-1: output-topic-1
      output-topic-2: output-topic-2
   topicsFields: 
      input-topic-1: insert_dt
      input-topic-2: upd_dt