#please note : no '-' is used
kafka:
   appId: kafka-algo-app-19 #This will define the appid
   bootstrapServers: |
      localhost:9092
   bootstrapServersTarget: |
      localhost:9092
   zookeeperHost: localhost
   defaultKeySerde: String
   defaultValueSerde: Avro
   appVersion: 70 #This will define the version
   appDeltaValue: 100
   appSmallDeltaValue: 100
   appSleepTimeMs: 5
   autoOffsetReset: earliest
   schemaRegistyUrl: http://localhost:8081/
   topics:
      input-topics: input-topic-1,input-topic-2
   topicsFields:
      input-topic-1: insert_dt
      input-topic-2: upd_dt
#       input-topic-1: default
#       input-topic-2: default