#please note : no '-' is used
kafka:
   bootstrapServers: |
      localhost:9092,localhost:9093
   bootstrapServersTarget: |
      localhost:9094,localhost:9095
   zookeeperHost: localhost
   defaultKeySerde: String
   defaultValueSerde: Avro
   appVersion: 1 #This will define the version
   zkNodeUpd: true
   appDeltaValue: 200
   appSmallDeltaValue: 100
   appSleepTimeMs: 10
   autoOffsetReset: earliest
   schemaRegistyUrl: http://localhost:8081/
   numConsumerThreads: 2
   topics:
      input-topics: input-topic-1,input-topic-2
   topicsFields:
#       input-topic-1: insert_dt
#       input-topic-2: upd_dt
      input-topic-1: default
      input-topic-2: default