name: Docker Build

# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/checkout@v1
    - run: mkdir -p target/
    - run: echo kafka-algorithm > target/kafka-algorithm-jar-with-dependencies.jar
    - uses: actions/upload-artifact@v1
      with:
        name: kafka-algorithm-jar-with-dependencies
        path: target/
      
  build-docker:
    runs-on: ubuntu-latest
    needs: build-jar
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: kafka-algorithm-jar-with-dependencies
        path: target/
      env:
        RELEASE_VERSION: $(date +%s) 
    - name: Env Setup
      env:
        RELEASE_VERSION: $(date +%s)
    - run: echo $RELEASE_VERSION
    - run: cat target/kafka-algorithm-jar-with-dependencies.jar
    - name: Docker Login
      run: echo '${{ secrets.DOCKERHUB_PASS }}' | docker login --username justinjoseph89 --password-stdin
    - name: Docker Build
      run: docker build . --file Dockerfile --tag justinjoseph89/kafka-algorithm:$RELEASE_VERSION
    - name: Docker Push
      run: docker push justinjoseph89/kafka-algorithm:$RELEASE_VERSION
    - name: Docker Run
      run: docker run -d --name=kafka-algo-app justinjoseph89/kafka-algorithm:$RELEASE_VERSION
